version: '3.8'
services:
  fhir-test-data-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./static/uploads:/app/static/uploads
      - ./test_data:/app/test_data
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - APP_MODE=lite
      - APP_BASE_URL=http://localhost:5000
      - TEST_DATA_FOLDER=/app/test_data
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
